[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
    "-C",
    "link-arg=-Tkernel/asm/aarch64/aarch64_linker.ld",
]
runner = [
    "sh",
    "-c",
    "rust-objcopy -O binary \"$0\" \"$0.bin\" && qemu-system-aarch64 -machine virt -cpu cortex-a72 -device ramfb -serial stdio -monitor none -d in_asm,int -D dynamix_asm.log -kernel \"$0.bin\""
]

[target.armv7a-none-eabi]
rustflags = [
    "-C",
    "link-args=-Tkernel/asm/armv7/armv7_linker.ld",
]
runner = [
    "sh",
    "-c",
    "rust-objcopy -O binary \"$0\" \"$0.bin\" && qemu-system-arm -machine virt -cpu cortex-a7 -device ramfb -serial stdio -monitor none -d in_asm,int -D dynamix_asm_v7.log -kernel \"$0.bin\""
]
