[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
    "-C",
    "link-arg=-Tkernel/aarch64/aarch64_linker.ld",
]
runner = [
    "sh",
    "-c",
    "rust-objcopy -O binary \"$0\" \"$0.bin\" && qemu-system-aarch64 -machine virt -cpu cortex-a72 -device ramfb -serial stdio -monitor none -kernel \"$0.bin\""
]